#! /usr/bin/expect

set bgpip [lindex $argv 0];
set bgpendpoint [lindex $argv 1];

spawn /bin/bash

expect "]# "
send "vtysh\n"
expect "# "
send "conf t\n"
expect "# "
send "router bgp 65300\n"
expect "# "
send "bgp router-id $bgpip\n"
expect "# "
send "bgp log-neighbor-changes\n"
expect "# "
send "no bgp default ipv4-unicast\n"
expect "# "
send "bgp default local-preference 150\n"
expect "# "
send "bgp default show-hostname\n"
expect "# "
send "no bgp network import-check\n"
expect "# "
send "neighbor $bgpendpoint remote-as 65300\n"
expect "# "
send "address-family ipv4 unicast\n"
expect "# "
send "neighbor $bgpendpoint activate\n"
expect "# "
send "exit-address-family\n"
expect "# "
send "exit\n"
expect "# "
send "exit\n"
expect "# "
send "write\n"
expect "# "
send "show bgp summary\n"
expect "# "
send "exit\n"
expect "# "